# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_0_0/design_1_xbip_dsp48_macro_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_0_0 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_conv_v1_0_2/design_1_conv_v1_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_conv_v1_0_2 || ORIG_REF_NAME==design_1_conv_v1_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_4_3/design_1_xbip_dsp48_macro_4_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_4_3 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_4_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_0_3/design_1_xbip_dsp48_macro_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_0_3 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_2_1/design_1_xbip_dsp48_macro_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_2_1 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_0_2/design_1_xbip_dsp48_macro_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_0_2 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_1_1/design_1_xbip_dsp48_macro_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_1_1 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_0_6/design_1_xbip_dsp48_macro_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_0_6 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_0_1/design_1_xbip_dsp48_macro_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_0_1 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_4_2/design_1_xbip_dsp48_macro_4_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_4_2 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_4_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_3_2/design_1_xbip_dsp48_macro_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_3_2 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_3_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_4_0/design_1_xbip_dsp48_macro_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_4_0 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_2_2/design_1_xbip_dsp48_macro_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_2_2 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_2_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_3_3/design_1_xbip_dsp48_macro_3_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_3_3 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_3_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_3_0/design_1_xbip_dsp48_macro_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_3_0 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_1_2/design_1_xbip_dsp48_macro_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_1_2 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_2_3/design_1_xbip_dsp48_macro_2_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_2_3 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_2_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_2_0/design_1_xbip_dsp48_macro_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_2_0 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_0_7/design_1_xbip_dsp48_macro_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_0_7 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_1_3/design_1_xbip_dsp48_macro_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_1_3 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_1_0/design_1_xbip_dsp48_macro_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_1_0 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_0_5/design_1_xbip_dsp48_macro_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_0_5 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_4_1/design_1_xbip_dsp48_macro_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_4_1 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_4_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_0_8/design_1_xbip_dsp48_macro_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_0_8 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_0_4/design_1_xbip_dsp48_macro_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_0_4 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_3_1/design_1_xbip_dsp48_macro_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_3_1 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
