set_property SRC_FILE_INFO {cfile:D:/Vivado/project/hw5_test10/hw5_test10.srcs/constrs_1/imports/xdc/pynq-z2_v1.0.xdc rfile:../../../hw5_test10.srcs/constrs_1/imports/xdc/pynq-z2_v1.0.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS33} [get_ports led4_b]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS33} [get_ports led5_g]
