# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/pynq-z2_v1.0.xdc

# Block Designs: bd/sort/sort.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sort || ORIG_REF_NAME==sort} -quiet] -quiet

# IP: bd/sort/ip/sort_processing_system7_0_0/sort_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sort_processing_system7_0_0 || ORIG_REF_NAME==sort_processing_system7_0_0} -quiet] -quiet

# IP: bd/sort/ip/sort_sort_0_0/sort_sort_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sort_sort_0_0 || ORIG_REF_NAME==sort_sort_0_0} -quiet] -quiet

# IP: bd/sort/ip/sort_ps7_0_axi_periph_0/sort_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sort_ps7_0_axi_periph_0 || ORIG_REF_NAME==sort_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/sort/ip/sort_rst_ps7_0_100M_0/sort_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sort_rst_ps7_0_100M_0 || ORIG_REF_NAME==sort_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/sort/ip/sort_auto_pc_0/sort_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sort_auto_pc_0 || ORIG_REF_NAME==sort_auto_pc_0} -quiet] -quiet

# XDC: bd/sort/sort_ooc.xdc
