# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/pynq-z2_v1.0.xdc

# Block Designs: bd/PWM/PWM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PWM || ORIG_REF_NAME==PWM} -quiet] -quiet

# IP: bd/PWM/ip/PWM_PWM_0_0/PWM_PWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PWM_PWM_0_0 || ORIG_REF_NAME==PWM_PWM_0_0} -quiet] -quiet

# IP: bd/PWM/ip/PWM_processing_system7_0_0/PWM_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PWM_processing_system7_0_0 || ORIG_REF_NAME==PWM_processing_system7_0_0} -quiet] -quiet

# IP: bd/PWM/ip/PWM_ps7_0_axi_periph_1/PWM_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PWM_ps7_0_axi_periph_1 || ORIG_REF_NAME==PWM_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/PWM/ip/PWM_rst_ps7_0_100M_1/PWM_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PWM_rst_ps7_0_100M_1 || ORIG_REF_NAME==PWM_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/PWM/ip/PWM_auto_pc_0/PWM_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PWM_auto_pc_0 || ORIG_REF_NAME==PWM_auto_pc_0} -quiet] -quiet

# XDC: bd/PWM/PWM_ooc.xdc
